changes

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -6,14 +6,6 @@ on:
 jobs:
   cypress-run:
     runs-on: windows-latest
-    strategy:
-      matrix:
-        group:
-          - "registration.js"
-          - "login_logout.js"
-          - "account_overview.js"
-          - "account_transations.js"
-      max-parallel: 4
 
     steps:
       - name: Checkout code
@@ -22,7 +14,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '16'  # Specify the Node.js version you use
+          node-version: '16'  # Adjust this to the Node.js version you use
 
       - name: Install dependencies
         run: npm install
@@ -32,7 +24,7 @@ jobs:
 
       - name: Run Cypress tests
         run: |
-          npx cypress run --spec "cypress/e2e/${{ matrix.group }}" || echo "Cypress tests failed"
+          npx cypress run --spec "cypress/e2e/**/*" || echo "Cypress tests failed"
 
       - name: Upload Cypress screenshots
         if: always()
